# Generated by Django 2.0.4 on 2018-06-24 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cast',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_movie', models.IntegerField()),
                ('title', models.CharField(max_length=200)),
                ('original_title', models.CharField(max_length=200)),
                ('overview', models.CharField(max_length=2000)),
                ('date', models.DateField()),
                ('director', models.CharField(max_length=100)),
                ('url_poster', models.CharField(max_length=300)),
                ('vote_average', models.DecimalField(decimal_places=2, max_digits=4)),
                ('url_video', models.CharField(max_length=300)),
                ('budget', models.DecimalField(decimal_places=2, max_digits=100)),
                ('revenue', models.DecimalField(decimal_places=2, max_digits=100)),
                ('original_language', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=20)),
                ('runtime', models.IntegerField()),
            ],
            options={
                'ordering': ('title',),
            },
        ),
        migrations.AddField(
            model_name='cast',
            name='movies',
            field=models.ManyToManyField(to='videoclub.Movie'),
        ),
    ]
